server:
  port: 9191
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:creditrama}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:docker}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        type: trace
